name: CI

on:
  push:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build podman image
        run: podman build -t flask-app:1.0.0 .

      - name: Run Flask container
        run: podman run --name localhost/flask-app:1.0.0 -d -p 5000:5000 flask-app

      - name: Wait for Flask to be ready
        run: |
          for i in {1..10}; do
            if curl --silent --fail http://localhost:5000/; then
              echo "Flask is up!"
              break
            fi
            echo "Waiting for Flask…"
            sleep 1
          done

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: tag and push image
        run: |
          podman tag localhost/flask-app:1.0.0 ghcr.io/${{ github.actor }}/${{ github.repository }}:latest
          podman push ghcr.io/${{ github.actor }}/${{ github.repository }}:latest

      - name: Teardown container
        if: always()
        run: |
          podman stop flask-test
          podman rm flask-test

